name: Compile and deploy PDF
on:
  push:
    branches:
      - master
    paths:
      - '*.tex'
      - '*.cls'

jobs:
  build:
    name: Compile and upload
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: iithesis.tex
      - name: Move paper to build directory
        run: mkdir build && mv iithesis.pdf build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: build
      - name: Send it with mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Master thesis ${{ github.sha }}
          body: Build job of ${{ github.repository }} completed successfully
          to: rossinek@gmail.com
          from: Self Mailer
          attachments: ./build/iithesis.pdf
